# This file is a template generator for Natron's issue tracker dashboard

# The blank template uses the old issue template
blank_issues_enabled: true

contact_links:
  - name: Read the contributing guidelines
    url: https://github.com/charlesangus/Natron/blob/main/CONTRIBUTING.md
    about: Not sure of how to contribute? Read the contributing guidelines to get started.
  - name: Get help on Natron's forum
    url: https://discuss.pixls.us/c/software/natron/27
    about: Have a ("how do I...?") question? Not sure if your issue is reproducible? The quickest way to get help is on Natron's community forum!
