name: Tests

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths-ignore:
      - Documentation
  pull_request:
    branches:
    - main
    paths-ignore:
      - Documentation

jobs:
  unix_test:
    name: Test Ubuntu Python 3.10
    runs-on: ubuntu-latest
    container:
      image: aswf/ci-baseqt:2027.0
    defaults:
      run:
        shell: bash -l {0}
    env:
      CI: 'True'
      PYTHON_VERSION: '3.10'
      OCIO_CONFIG_VERSION: 2.5
      NATRON_IN_CONTAINER: 1

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Fetch test assets
        run: tools/ci/local/fetch-assets.sh

      - name: Build Unix (debug)
        run: tools/ci/local/build.sh debug

      - name: Run Unix Tests (debug)
        run: tools/ci/local/test.sh ctest debug
